export const techSkills: string[] = [
    "HTML",
    "CSS",
    "Bootstrap",
    "JavaScript",
    "Typescript",
    "ES6",
    "jQuery",
    "Ajax",
    "JSON",
    "RESTful API",
    "REST API",
    "React",
    "Node.Js",
    "Maven",
    "Java SE",
    "Java EE (Servlets, JSP, J2EE)",
    "File I/O",
    "MVC",
    "Spring Boot",
    "Hibernate",
    "MySQL",
    "Thymeleaf",
    "OOP",
    "TDD",
    "Version Control with Git",
    "Paired Programming",
    "Agile Methodologies",
    "Debugging",
    "AWS Deployment",
    "Apache TomCat",
    "Unit Testing (JUnit)",
    'Next.js',
    "Tailwind CSS",
  ];
  
  export const softSkills: string[] = [
    'Communication',
    'Teamwork',
    'Problem Solving',
    'Time Management',
    'Critical Thinking',
    'Adaptability',
    'Conflict Resolution',
    'Leadership',
    'Creativity',
    'Work Ethic',
    'Interpersonal Skills',
    'Empathy',
    'Touble Shooting'
  ];