// file is used to export all components from one place
export { default  as HeroSection } from './hero_section/HeroSection'
export { default as Navbar } from './navbar/NavBar'
export { default as WorkHistory } from './work_history/WorkHistory'
export { default as SkillsSection } from './skills_section/SkillsSection'
export { default as SideBar } from './sidebar/SideBar'
export { default as Footer } from './footer/Footer'
export { default as CvSection } from './cv_section/CvSection'
export { default as Projects } from './projects/Projects'
export { default as MainSection } from './main_Section/MainSection'
